/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pietra;

import Dao.Usuario;
import Dao.Cliente;
import Dao.Pedido;
import Dao.Item;
import Dao.Representante;
import Dao.UsuarioDAO;
import java.util.List;
import javax.swing.JList;

/**
 *
 * @author viniciusfurlanetto
 */
public class lookup extends javax.swing.JPanel {
    IterableList<Usuario> ObjListU;
    IterableList<Pedido> ObjListP;
    IterableList<Cliente> ObjListC;
    IterableList<Representante> ObjListR;
    IterableList<Item> ObjListI;
    
    List<Usuario> ObjList;
    UsuarioDAO ObjDAO = new UsuarioDAO ();
    
    /**
     * Creates new form lookup
     */
    
    
    public lookup() {
        initComponents();
        
        
        
        ObjList = ObjDAO.pPreencheListUsuario();
        ObjListU = new IterableList <> (ObjList);
        
        JList Lista = new JList<>();
    }

    public void pIniciaLista(){
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnConfirmar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        BtnConfirmar.setText("Confirmar");
        BtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(BtnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(BtnCancelar)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnConfirmar)
                    .addComponent(BtnCancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnConfirmar;
    // End of variables declaration//GEN-END:variables
}
